using AutoLot.Domain.Common;

namespace AutoLot.Application.Common.Localization;

/// <summary>
/// Тексти повідомлень обома мовами.
///
/// Словник, а не файли ресурсів: двом мовам сателітні збірки й тулінг .resx
/// дають більше клопоту, ніж користі, а тут усе видно в одному місці — так
/// само, як у словнику фронтенду.
/// </summary>
public static class MessageCatalog
{
    private static readonly Dictionary<string, string> Ukrainian = new(StringComparer.Ordinal)
    {
        [MessageCodes.AuthEmailRequired] = "Вкажіть email.",
        [MessageCodes.AuthEmailTooLong] = "Email задовгий.",
        [MessageCodes.AuthEmailMalformed] = "Email виглядає некоректним.",
        [MessageCodes.AuthPasswordRequired] = "Вкажіть пароль.",
        [MessageCodes.AuthPasswordTooShort] = "Пароль має містити щонайменше 8 символів.",
        [MessageCodes.AuthPasswordTooLong] = "Пароль задовгий.",
        [MessageCodes.AuthPasswordNeedsLower] = "Пароль має містити малу літеру.",
        [MessageCodes.AuthPasswordNeedsUpper] = "Пароль має містити велику літеру.",
        [MessageCodes.AuthPasswordNeedsDigit] = "Пароль має містити цифру.",
        [MessageCodes.AuthDisplayNameRequired] = "Вкажіть ім'я або назву салону.",
        [MessageCodes.AuthDisplayNameTooShort] = "Ім'я закоротке.",
        [MessageCodes.AuthDisplayNameTooLong] = "Ім'я задовге.",
        [MessageCodes.AuthAccountTypeUnknown] = "Невідомий тип акаунта.",
        [MessageCodes.AuthPhoneFormat] = "Телефон має бути у форматі +380XXXXXXXXX.",
        [MessageCodes.RecoveryEmailRequired] = "Вкажіть пошту.",
        [MessageCodes.RecoveryEmailMalformed] = "Пошта виглядає некоректною.",
        [MessageCodes.RecoveryEmailTooLong] = "Адреса задовга.",
        [MessageCodes.RecoveryTokenIncomplete] = "Посилання неповне — скористайтеся тим, що в листі.",
        [MessageCodes.RecoveryPasswordRequired] = "Вкажіть новий пароль.",
        [MessageCodes.PlaceCityInvalid] = "Ідентифікатор міста некоректний.",
        [MessageCodes.PlaceDistrictInvalid] = "Ідентифікатор району міста некоректний.",
        [MessageCodes.PlaceCityFirst] = "Спершу вкажіть місто.",
        [MessageCodes.ProfileDisplayNameRequired] = "Вкажіть, як до вас звертатися.",
        [MessageCodes.CarVinFormat] = "VIN складається з 17 символів; літери I, O та Q в ньому не використовуються.",
        [MessageCodes.CarMakeRequired] = "Оберіть марку.",
        [MessageCodes.CarModelRequired] = "Оберіть модель.",
        [MessageCodes.CarGenerationInvalid] = "Некоректне покоління.",
        [MessageCodes.CarFeaturesDuplicate] = "Одна опція вказана двічі.",
        [MessageCodes.CarFeaturesInvalid] = "Некоректна опція комплектації.",
        [MessageCodes.CarConditionUnknown] = "Невідомий стан авто.",
        [MessageCodes.CarMileageRequired] = "Вкажіть пробіг.",
        [MessageCodes.CarMileageUnrealistic] = "Пробіг виглядає нереальним.",
        [MessageCodes.CarMileageNewTooHigh] = "Для нового авто пробіг не може бути таким великим.",
        [MessageCodes.CarOwnersNewHasNone] = "У нового авто ще не було власників.",
        [MessageCodes.CarOwnersUnrealistic] = "Кількість власників виглядає нереальною.",
        [MessageCodes.CarFuelUnknown] = "Невідомий тип пального.",
        [MessageCodes.CarTransmissionUnknown] = "Невідомий тип коробки передач.",
        [MessageCodes.CarDrivetrainUnknown] = "Невідомий тип приводу.",
        [MessageCodes.CarEngineRequired] = "Вкажіть об'єм двигуна.",
        [MessageCodes.CarEngineNotForElectric] = "В електромобіля немає об'єму двигуна.",
        [MessageCodes.CarEngineRange] = "Об'єм двигуна має бути від 0,1 до 12 літрів.",
        [MessageCodes.CarPowerRange] = "Потужність має бути від 1 до 2000 к.с.",
        [MessageCodes.CarConsumptionCityUnrealistic] = "Витрата в місті виглядає нереальною.",
        [MessageCodes.CarConsumptionHighwayUnrealistic] = "Витрата на шосе виглядає нереальною.",
        [MessageCodes.CarConsumptionCombinedUnrealistic] = "Змішана витрата виглядає нереальною.",
        [MessageCodes.CarConsumptionNotForElectric] = "Електромобіль не витрачає пального.",
        [MessageCodes.CarBatteryRequired] = "Вкажіть ємність батареї.",
        [MessageCodes.CarBatteryOnlyElectric] = "Батарея буває лише в електромобіля або гібрида.",
        [MessageCodes.CarBatteryRange] = "Ємність батареї має бути від 1 до 300 кВт·год.",
        [MessageCodes.CarRangeUnrealistic] = "Запас ходу виглядає нереальним.",
        [MessageCodes.CarRangeNeedsBattery] = "Запас ходу вказують лише там, де є батарея.",
        [MessageCodes.CarChargingPortNeedsBattery] = "Зарядний роз'єм буває лише там, де є батарея.",
        [MessageCodes.CarChargingPortUnknown] = "Невідомий тип зарядного роз'єму.",
        [MessageCodes.CarBodyUnknown] = "Невідомий тип кузова.",
        [MessageCodes.CarColourUnknown] = "Невідомий колір.",
        [MessageCodes.CarDamageUnknown] = "Невідомий стан пошкодження.",
        [MessageCodes.CarSeatsRange] = "Кількість місць має бути від 1 до 9.",
        [MessageCodes.CarDoorsRange] = "Кількість дверей має бути від 2 до 6.",
        [MessageCodes.CarEcologyUnknown] = "Невідомий екологічний стандарт.",
        [MessageCodes.CarPaintUnknown] = "Невідомий стан лакофарбового покриття.",
        [MessageCodes.CarImportedFromInvalid] = "Некоректна країна пригону.",
        [MessageCodes.CarManufacturerCountryInvalid] = "Некоректна країна-виробник.",
        [MessageCodes.ListingTitleRequired] = "Вкажіть заголовок.",
        [MessageCodes.ListingTitleTooShort] = "Заголовок закороткий.",
        [MessageCodes.ListingTitleTooLong] = "Заголовок задовгий.",
        [MessageCodes.ListingDescriptionRequired] = "Додайте опис.",
        [MessageCodes.ListingDescriptionTooShort] = "Опис закороткий.",
        [MessageCodes.ListingDescriptionTooLong] = "Опис задовгий.",
        [MessageCodes.ListingCityRequired] = "Оберіть місто.",
        [MessageCodes.ListingDistrictInvalid] = "Некоректний район міста.",
        [MessageCodes.ListingPricePositive] = "Ціна має бути більшою за нуль.",
        [MessageCodes.ListingPriceUnrealistic] = "Ціна виглядає помилковою.",
        [MessageCodes.ListingCurrencyUnknown] = "Невідома валюта.",
        [MessageCodes.ListingTypeUnknown] = "Невідомий тип оголошення.",
        [MessageCodes.ListingReserveBelowStart] = "Резервна ціна не може бути нижчою за стартову.",
        [MessageCodes.ListingReserveAuctionOnly] = "Резервна ціна буває лише в лота з торгами.",
        [MessageCodes.ModerationReasonRequired] = "Вкажіть причину відмови.",
        [MessageCodes.ModerationReasonTooShort] = "Причина має пояснювати, що виправити.",
        [MessageCodes.ModerationReasonTooLong] = "Причина задовга.",
        [MessageCodes.QuestionTextRequired] = "Питання не може бути порожнім.",
        [MessageCodes.QuestionTextTooShort] = "Питання надто коротке.",
        [MessageCodes.QuestionTextTooLong] = "Питання задовге — до 1000 символів.",
        [MessageCodes.QuestionAnswerRequired] = "Відповідь не може бути порожньою.",
        [MessageCodes.QuestionAnswerTooLong] = "Відповідь задовга — до 2000 символів.",
        [MessageCodes.ReportReasonRequired] = "Оберіть причину зі списку.",
        [MessageCodes.ReportCommentTooLong] = "Пояснення задовге — до 1000 символів.",
        [MessageCodes.ReportCommentRequired] = "Опишіть, у чому річ.",
        [MessageCodes.ReportNoteTooLong] = "Нотатка задовга — до 1000 символів.",
        [MessageCodes.CatalogPageMin] = "Номер сторінки починається з одиниці.",
        [MessageCodes.CatalogTextTooLong] = "Пошуковий запит задовгий.",
        [MessageCodes.CatalogSortUnknown] = "Невідомий порядок сортування.",
        [MessageCodes.CatalogPriceRange] = "Нижня межа ціни більша за верхню.",
        [MessageCodes.CatalogYearRange] = "Нижня межа року більша за верхню.",
        [MessageCodes.CatalogMileageRange] = "Нижня межа пробігу більша за верхню.",
        [MessageCodes.CatalogEngineRange] = "Нижня межа об'єму більша за верхню.",
        [MessageCodes.CatalogPowerRange] = "Нижня межа потужності більша за верхню.",
        [MessageCodes.ChatMessageRequired] = "Повідомлення не може бути порожнім.",
        [MessageCodes.ChatMessageTooLong] = "Повідомлення задовге — до 4000 символів.",
        [MessageCodes.SavedSearchNameRequired] = "Дайте пошуку назву.",
    };

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        [MessageCodes.AuthEmailRequired] = "Enter an e-mail address.",
        [MessageCodes.AuthEmailTooLong] = "That e-mail address is too long.",
        [MessageCodes.AuthEmailMalformed] = "That e-mail address does not look right.",
        [MessageCodes.AuthPasswordRequired] = "Enter a password.",
        [MessageCodes.AuthPasswordTooShort] = "The password must be at least 8 characters long.",
        [MessageCodes.AuthPasswordTooLong] = "That password is too long.",
        [MessageCodes.AuthPasswordNeedsLower] = "The password must contain a lower-case letter.",
        [MessageCodes.AuthPasswordNeedsUpper] = "The password must contain an upper-case letter.",
        [MessageCodes.AuthPasswordNeedsDigit] = "The password must contain a digit.",
        [MessageCodes.AuthDisplayNameRequired] = "Enter your name or the dealership's name.",
        [MessageCodes.AuthDisplayNameTooShort] = "That name is too short.",
        [MessageCodes.AuthDisplayNameTooLong] = "That name is too long.",
        [MessageCodes.AuthAccountTypeUnknown] = "Unknown account type.",
        [MessageCodes.AuthPhoneFormat] = "The phone number must be in the format +380XXXXXXXXX.",
        [MessageCodes.RecoveryEmailRequired] = "Enter your e-mail address.",
        [MessageCodes.RecoveryEmailMalformed] = "That e-mail address does not look right.",
        [MessageCodes.RecoveryEmailTooLong] = "That address is too long.",
        [MessageCodes.RecoveryTokenIncomplete] = "The link is incomplete — use the one from the letter.",
        [MessageCodes.RecoveryPasswordRequired] = "Enter a new password.",
        [MessageCodes.PlaceCityInvalid] = "That city identifier is not valid.",
        [MessageCodes.PlaceDistrictInvalid] = "That city district identifier is not valid.",
        [MessageCodes.PlaceCityFirst] = "Choose a city first.",
        [MessageCodes.ProfileDisplayNameRequired] = "Tell us what to call you.",
        [MessageCodes.CarVinFormat] = "A VIN is 17 characters long and never contains the letters I, O or Q.",
        [MessageCodes.CarMakeRequired] = "Choose a make.",
        [MessageCodes.CarModelRequired] = "Choose a model.",
        [MessageCodes.CarGenerationInvalid] = "That generation is not valid.",
        [MessageCodes.CarFeaturesDuplicate] = "One of the features is listed twice.",
        [MessageCodes.CarFeaturesInvalid] = "That feature is not valid.",
        [MessageCodes.CarConditionUnknown] = "Unknown condition.",
        [MessageCodes.CarMileageRequired] = "Enter the mileage.",
        [MessageCodes.CarMileageUnrealistic] = "That mileage does not look realistic.",
        [MessageCodes.CarMileageNewTooHigh] = "A new car cannot have mileage that high.",
        [MessageCodes.CarOwnersNewHasNone] = "A new car has not had any owners yet.",
        [MessageCodes.CarOwnersUnrealistic] = "That number of owners does not look realistic.",
        [MessageCodes.CarFuelUnknown] = "Unknown fuel type.",
        [MessageCodes.CarTransmissionUnknown] = "Unknown transmission type.",
        [MessageCodes.CarDrivetrainUnknown] = "Unknown drivetrain type.",
        [MessageCodes.CarEngineRequired] = "Enter the engine size.",
        [MessageCodes.CarEngineNotForElectric] = "An electric car has no engine size.",
        [MessageCodes.CarEngineRange] = "The engine size must be between 0.1 and 12 litres.",
        [MessageCodes.CarPowerRange] = "Power must be between 1 and 2000 hp.",
        [MessageCodes.CarConsumptionCityUnrealistic] = "That urban consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionHighwayUnrealistic] = "That motorway consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionCombinedUnrealistic] = "That combined consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionNotForElectric] = "An electric car does not consume fuel.",
        [MessageCodes.CarBatteryRequired] = "Enter the battery capacity.",
        [MessageCodes.CarBatteryOnlyElectric] = "Only an electric car or a hybrid has a battery.",
        [MessageCodes.CarBatteryRange] = "Battery capacity must be between 1 and 300 kWh.",
        [MessageCodes.CarRangeUnrealistic] = "That range does not look realistic.",
        [MessageCodes.CarRangeNeedsBattery] = "Range is only given where there is a battery.",
        [MessageCodes.CarChargingPortNeedsBattery] = "A charging port only exists where there is a battery.",
        [MessageCodes.CarChargingPortUnknown] = "Unknown charging port type.",
        [MessageCodes.CarBodyUnknown] = "Unknown body type.",
        [MessageCodes.CarColourUnknown] = "Unknown colour.",
        [MessageCodes.CarDamageUnknown] = "Unknown damage state.",
        [MessageCodes.CarSeatsRange] = "The number of seats must be between 1 and 9.",
        [MessageCodes.CarDoorsRange] = "The number of doors must be between 2 and 6.",
        [MessageCodes.CarEcologyUnknown] = "Unknown emission standard.",
        [MessageCodes.CarPaintUnknown] = "Unknown paint condition.",
        [MessageCodes.CarImportedFromInvalid] = "That country of import is not valid.",
        [MessageCodes.CarManufacturerCountryInvalid] = "That country of manufacture is not valid.",
        [MessageCodes.ListingTitleRequired] = "Enter a title.",
        [MessageCodes.ListingTitleTooShort] = "That title is too short.",
        [MessageCodes.ListingTitleTooLong] = "That title is too long.",
        [MessageCodes.ListingDescriptionRequired] = "Add a description.",
        [MessageCodes.ListingDescriptionTooShort] = "That description is too short.",
        [MessageCodes.ListingDescriptionTooLong] = "That description is too long.",
        [MessageCodes.ListingCityRequired] = "Choose a city.",
        [MessageCodes.ListingDistrictInvalid] = "That city district is not valid.",
        [MessageCodes.ListingPricePositive] = "The price must be greater than zero.",
        [MessageCodes.ListingPriceUnrealistic] = "That price looks like a mistake.",
        [MessageCodes.ListingCurrencyUnknown] = "Unknown currency.",
        [MessageCodes.ListingTypeUnknown] = "Unknown listing type.",
        [MessageCodes.ListingReserveBelowStart] = "The reserve price cannot be lower than the starting price.",
        [MessageCodes.ListingReserveAuctionOnly] = "Only an auction lot has a reserve price.",
        [MessageCodes.ModerationReasonRequired] = "Give a reason for the rejection.",
        [MessageCodes.ModerationReasonTooShort] = "The reason should explain what needs fixing.",
        [MessageCodes.ModerationReasonTooLong] = "That reason is too long.",
        [MessageCodes.QuestionTextRequired] = "A question cannot be empty.",
        [MessageCodes.QuestionTextTooShort] = "That question is too short.",
        [MessageCodes.QuestionTextTooLong] = "That question is too long — 1000 characters at most.",
        [MessageCodes.QuestionAnswerRequired] = "An answer cannot be empty.",
        [MessageCodes.QuestionAnswerTooLong] = "That answer is too long — 2000 characters at most.",
        [MessageCodes.ReportReasonRequired] = "Choose a reason from the list.",
        [MessageCodes.ReportCommentTooLong] = "That explanation is too long — 1000 characters at most.",
        [MessageCodes.ReportCommentRequired] = "Describe what the problem is.",
        [MessageCodes.ReportNoteTooLong] = "That note is too long — 1000 characters at most.",
        [MessageCodes.CatalogPageMin] = "Page numbers start at one.",
        [MessageCodes.CatalogTextTooLong] = "That search query is too long.",
        [MessageCodes.CatalogSortUnknown] = "Unknown sort order.",
        [MessageCodes.CatalogPriceRange] = "The lower price bound is above the upper one.",
        [MessageCodes.CatalogYearRange] = "The lower year bound is above the upper one.",
        [MessageCodes.CatalogMileageRange] = "The lower mileage bound is above the upper one.",
        [MessageCodes.CatalogEngineRange] = "The lower engine-size bound is above the upper one.",
        [MessageCodes.CatalogPowerRange] = "The lower power bound is above the upper one.",
        [MessageCodes.ChatMessageRequired] = "A message cannot be empty.",
        [MessageCodes.ChatMessageTooLong] = "That message is too long — 4000 characters at most.",
        [MessageCodes.SavedSearchNameRequired] = "Give the search a name.",
    };

    /// <summary>Коди, для яких є переклад. Потрібно тестам.</summary>
    public static IReadOnlyCollection<string> Codes => Ukrainian.Keys;

    /// <summary>
    /// Перекладає код. Незнайомий рядок повертається як є — і це навмисно:
    /// так повідомлення, яке ще не перевели на коди, показується старим
    /// текстом замість того, щоб зникнути або перетворитися на «null».
    /// </summary>
    public static string Translate(string codeOrText, string language)
    {
        var table = LanguageCodes.Normalize(language) == LanguageCodes.English ? English : Ukrainian;

        return table.TryGetValue(codeOrText, out var text) ? text : codeOrText;
    }
}
