using System.Globalization;
using System.Text.RegularExpressions;
using AutoLot.Domain.Common;

namespace AutoLot.Application.Common.Localization;

/// <summary>
/// Тексти повідомлень обома мовами.
///
/// Словник, а не файли ресурсів: двом мовам сателітні збірки й тулінг .resx
/// дають більше клопоту, ніж користі, а тут усе видно в одному місці — так
/// само, як у словнику фронтенду.
/// </summary>
public static partial class MessageCatalog
{
    private static readonly Dictionary<string, string> Ukrainian = new(StringComparer.Ordinal)
    {
        [MessageCodes.AuthEmailRequired] = "Вкажіть email.",
        [MessageCodes.AuthEmailTooLong] = "Email задовгий.",
        [MessageCodes.AuthEmailMalformed] = "Email виглядає некоректним.",
        [MessageCodes.AuthPasswordRequired] = "Вкажіть пароль.",
        [MessageCodes.AuthPasswordTooShort] = "Пароль має містити щонайменше 8 символів.",
        [MessageCodes.AuthPasswordTooLong] = "Пароль задовгий.",
        [MessageCodes.AuthPasswordNeedsLower] = "Пароль має містити малу літеру.",
        [MessageCodes.AuthPasswordNeedsUpper] = "Пароль має містити велику літеру.",
        [MessageCodes.AuthPasswordNeedsDigit] = "Пароль має містити цифру.",
        [MessageCodes.AuthDisplayNameRequired] = "Вкажіть ім'я або назву салону.",
        [MessageCodes.AuthDisplayNameTooShort] = "Ім'я закоротке.",
        [MessageCodes.AuthDisplayNameTooLong] = "Ім'я задовге.",
        [MessageCodes.AuthAccountTypeUnknown] = "Невідомий тип акаунта.",
        [MessageCodes.AuthPhoneFormat] = "Телефон має бути у форматі +380XXXXXXXXX.",
        [MessageCodes.RecoveryEmailRequired] = "Вкажіть пошту.",
        [MessageCodes.RecoveryEmailMalformed] = "Пошта виглядає некоректною.",
        [MessageCodes.RecoveryEmailTooLong] = "Адреса задовга.",
        [MessageCodes.RecoveryTokenIncomplete] = "Посилання неповне — скористайтеся тим, що в листі.",
        [MessageCodes.RecoveryPasswordRequired] = "Вкажіть новий пароль.",
        [MessageCodes.PlaceCityInvalid] = "Ідентифікатор міста некоректний.",
        [MessageCodes.PlaceDistrictInvalid] = "Ідентифікатор району міста некоректний.",
        [MessageCodes.PlaceCityFirst] = "Спершу вкажіть місто.",
        [MessageCodes.ProfileDisplayNameRequired] = "Вкажіть, як до вас звертатися.",
        [MessageCodes.CarVinFormat] = "VIN складається з 17 символів; літери I, O та Q в ньому не використовуються.",
        [MessageCodes.CarMakeRequired] = "Оберіть марку.",
        [MessageCodes.CarModelRequired] = "Оберіть модель.",
        [MessageCodes.CarGenerationInvalid] = "Некоректне покоління.",
        [MessageCodes.CarFeaturesDuplicate] = "Одна опція вказана двічі.",
        [MessageCodes.CarFeaturesInvalid] = "Некоректна опція комплектації.",
        [MessageCodes.CarConditionUnknown] = "Невідомий стан авто.",
        [MessageCodes.CarMileageRequired] = "Вкажіть пробіг.",
        [MessageCodes.CarMileageUnrealistic] = "Пробіг виглядає нереальним.",
        [MessageCodes.CarMileageNewTooHigh] = "Для нового авто пробіг не може бути таким великим.",
        [MessageCodes.CarOwnersNewHasNone] = "У нового авто ще не було власників.",
        [MessageCodes.CarOwnersUnrealistic] = "Кількість власників виглядає нереальною.",
        [MessageCodes.CarFuelUnknown] = "Невідомий тип пального.",
        [MessageCodes.CarTransmissionUnknown] = "Невідомий тип коробки передач.",
        [MessageCodes.CarDrivetrainUnknown] = "Невідомий тип приводу.",
        [MessageCodes.CarEngineRequired] = "Вкажіть об'єм двигуна.",
        [MessageCodes.CarEngineNotForElectric] = "В електромобіля немає об'єму двигуна.",
        [MessageCodes.CarEngineRange] = "Об'єм двигуна має бути від 0,1 до 12 літрів.",
        [MessageCodes.CarPowerRange] = "Потужність має бути від 1 до 2000 к.с.",
        [MessageCodes.CarConsumptionCityUnrealistic] = "Витрата в місті виглядає нереальною.",
        [MessageCodes.CarConsumptionHighwayUnrealistic] = "Витрата на шосе виглядає нереальною.",
        [MessageCodes.CarConsumptionCombinedUnrealistic] = "Змішана витрата виглядає нереальною.",
        [MessageCodes.CarConsumptionNotForElectric] = "Електромобіль не витрачає пального.",
        [MessageCodes.CarBatteryRequired] = "Вкажіть ємність батареї.",
        [MessageCodes.CarBatteryOnlyElectric] = "Батарея буває лише в електромобіля або гібрида.",
        [MessageCodes.CarBatteryRange] = "Ємність батареї має бути від 1 до 300 кВт·год.",
        [MessageCodes.CarRangeUnrealistic] = "Запас ходу виглядає нереальним.",
        [MessageCodes.CarRangeNeedsBattery] = "Запас ходу вказують лише там, де є батарея.",
        [MessageCodes.CarChargingPortNeedsBattery] = "Зарядний роз'єм буває лише там, де є батарея.",
        [MessageCodes.CarChargingPortUnknown] = "Невідомий тип зарядного роз'єму.",
        [MessageCodes.CarBodyUnknown] = "Невідомий тип кузова.",
        [MessageCodes.CarColourUnknown] = "Невідомий колір.",
        [MessageCodes.CarDamageUnknown] = "Невідомий стан пошкодження.",
        [MessageCodes.CarSeatsRange] = "Кількість місць має бути від 1 до 9.",
        [MessageCodes.CarDoorsRange] = "Кількість дверей має бути від 2 до 6.",
        [MessageCodes.CarEcologyUnknown] = "Невідомий екологічний стандарт.",
        [MessageCodes.CarPaintUnknown] = "Невідомий стан лакофарбового покриття.",
        [MessageCodes.CarImportedFromInvalid] = "Некоректна країна пригону.",
        [MessageCodes.CarManufacturerCountryInvalid] = "Некоректна країна-виробник.",
        [MessageCodes.ListingTitleRequired] = "Вкажіть заголовок.",
        [MessageCodes.ListingTitleTooShort] = "Заголовок закороткий.",
        [MessageCodes.ListingTitleTooLong] = "Заголовок задовгий.",
        [MessageCodes.ListingDescriptionRequired] = "Додайте опис.",
        [MessageCodes.ListingDescriptionTooShort] = "Опис закороткий.",
        [MessageCodes.ListingDescriptionTooLong] = "Опис задовгий.",
        [MessageCodes.ListingCityRequired] = "Оберіть місто.",
        [MessageCodes.ListingDistrictInvalid] = "Некоректний район міста.",
        [MessageCodes.ListingPricePositive] = "Ціна має бути більшою за нуль.",
        [MessageCodes.ListingPriceUnrealistic] = "Ціна виглядає помилковою.",
        [MessageCodes.ListingCurrencyUnknown] = "Невідома валюта.",
        [MessageCodes.ListingTypeUnknown] = "Невідомий тип оголошення.",
        [MessageCodes.ListingReserveBelowStart] = "Резервна ціна не може бути нижчою за стартову.",
        [MessageCodes.ListingReserveAuctionOnly] = "Резервна ціна буває лише в лота з торгами.",
        [MessageCodes.ModerationReasonRequired] = "Вкажіть причину відмови.",
        [MessageCodes.ModerationReasonTooShort] = "Причина має пояснювати, що виправити.",
        [MessageCodes.ModerationReasonTooLong] = "Причина задовга.",
        [MessageCodes.QuestionTextRequired] = "Питання не може бути порожнім.",
        [MessageCodes.QuestionTextTooShort] = "Питання надто коротке.",
        [MessageCodes.QuestionTextTooLong] = "Питання задовге — до 1000 символів.",
        [MessageCodes.QuestionAnswerRequired] = "Відповідь не може бути порожньою.",
        [MessageCodes.QuestionAnswerTooLong] = "Відповідь задовга — до 2000 символів.",
        [MessageCodes.ReportReasonRequired] = "Оберіть причину зі списку.",
        [MessageCodes.ReportCommentTooLong] = "Пояснення задовге — до 1000 символів.",
        [MessageCodes.ReportCommentRequired] = "Опишіть, у чому річ.",
        [MessageCodes.ReportNoteTooLong] = "Нотатка задовга — до 1000 символів.",
        [MessageCodes.CatalogPageMin] = "Номер сторінки починається з одиниці.",
        [MessageCodes.CatalogTextTooLong] = "Пошуковий запит задовгий.",
        [MessageCodes.CatalogSortUnknown] = "Невідомий порядок сортування.",
        [MessageCodes.CatalogPriceRange] = "Нижня межа ціни більша за верхню.",
        [MessageCodes.CatalogYearRange] = "Нижня межа року більша за верхню.",
        [MessageCodes.CatalogMileageRange] = "Нижня межа пробігу більша за верхню.",
        [MessageCodes.CatalogEngineRange] = "Нижня межа об'єму більша за верхню.",
        [MessageCodes.CatalogPowerRange] = "Нижня межа потужності більша за верхню.",
        [MessageCodes.ChatMessageRequired] = "Повідомлення не може бути порожнім.",
        [MessageCodes.ChatMessageTooLong] = "Повідомлення задовге — до 4000 символів.",
        [MessageCodes.SavedSearchNameRequired] = "Дайте пошуку назву.",
        [MessageCodes.ListingSubmitWrongStatus] = "На модерацію можна подати лише чернетку або відхилене оголошення.",
        [MessageCodes.ListingApproveWrongStatus] = "Схвалити можна лише оголошення, подане на модерацію.",
        [MessageCodes.ListingRejectWrongStatus] = "Відхилити можна лише оголошення, подане на модерацію.",
        [MessageCodes.ListingUnpublishWrongStatus] = "Зняти з публікації можна лише оголошення, яке в ній є.",
        [MessageCodes.ListingSoldWrongStatus] = "Проданим можна позначити лише активне оголошення.",
        [MessageCodes.ListingSoldSellerIsBuyer] = "Продавець не може бути покупцем.",
        [MessageCodes.ListingArchiveAlready] = "Оголошення вже в архіві.",
        [MessageCodes.ListingArchiveDraft] = "Чернетку не архівують — її видаляють.",
        [MessageCodes.ListingRestoreWrongStatus] = "Відновити можна лише архівне оголошення.",
        [MessageCodes.ListingEditWrongStatus] = "Редагувати можна лише чернетку або відхилене оголошення.",
        [MessageCodes.ListingDeleteDraftOnly] = "Видалити можна лише чернетку; опубліковане оголошення архівують.",
        [MessageCodes.ListingAccessOtherSeller] = "Це оголошення належить іншому продавцеві.",
        [MessageCodes.ListingBuyerNeverWrote] = "Ця людина не листувалася про це авто, тож покупцем бути не може.",
        [MessageCodes.ListingLimitReached] = "Ваш тариф дозволяє {limit} активних оголошень. Архівуйте старі або перейдіть на вищий тариф.",
        [MessageCodes.CarModelWrongMake] = "Обрана модель не належить цій марці.",
        [MessageCodes.CarGenerationWrongModel] = "Обране покоління не належить цій моделі.",
        [MessageCodes.CarFeaturesUnknownSome] = "Серед обраних опцій є невідомі.",
        [MessageCodes.PlaceCityOrDistrictInvalid] = "Такого міста немає або вказаний район належить іншому місту.",
        [MessageCodes.PhotoNotAnImage] = "Файл не є зображенням.",
        [MessageCodes.PhotoFormatUnsupported] = "Підтримуються лише JPEG, PNG і WebP.",
        [MessageCodes.PhotoResolutionTooBig] = "Зображення завелике за роздільною здатністю.",
        [MessageCodes.PhotoCorrupt] = "Файл пошкоджений або не є зображенням.",
        [MessageCodes.PhotoOrderMustListAll] = "Перелік має містити всі фото оголошення рівно по разу.",
        [MessageCodes.PhotoLimitReached] = "До оголошення можна додати не більше {limit} фото.",
        [MessageCodes.PhotoTooLarge] = "Файл завеликий: максимум {limit} МБ.",
        [MessageCodes.QuestionSelf] = "Питати самого себе не можна — відповідайте на чужі.",
        [MessageCodes.QuestionAnswerSellerOnly] = "Відповідати на питання може лише продавець.",
        [MessageCodes.ReportOwnListing] = "Це ваше оголошення.",
        [MessageCodes.ReportAlreadyResolved] = "Скаргу вже розглянуто.",
        [MessageCodes.ReviewSelf] = "Відгук самому собі не має сенсу.",
        [MessageCodes.ReviewPartiesOnly] = "Відгук лишають сторони угоди — продавець і покупець.",
        [MessageCodes.ReviewAlready] = "Ви вже лишили відгук про цю угоду.",
        [MessageCodes.ReviewRatingRange] = "Оцінка має бути від {min} до {max}.",
        [MessageCodes.AuctionBidTooLow] = "Ставка має бути щонайменше {minimum} — це поточна ціна плюс крок.",
        [MessageCodes.AuctionCeilingTooLow] = "Нова стеля має бути вищою за попередню.",
        [MessageCodes.AuctionFinished] = "Торги вже завершені.",
        [MessageCodes.AuctionTimeUp] = "Час торгів вичерпано.",
        [MessageCodes.AuctionStillRunning] = "Торги ще тривають — закривати зарано.",
        [MessageCodes.AuctionOwnLot] = "Ставити на власний лот не можна.",
        [MessageCodes.WalletTopUpPositive] = "Сума поповнення має бути додатною.",
        [MessageCodes.WalletChargePositive] = "Сума списання має бути додатною.",
        [MessageCodes.WalletTopUpMax] = "За раз можна поповнити не більше {limit}.",
        [MessageCodes.BillingBasicNoOrder] = "Базовий тариф діє без оформлення — просто дочекайтеся кінця платного.",
        [MessageCodes.BillingPlanWaitForEnd] = "Спершу має завершитися чинний тариф — переходи посеред періоду не передбачені.",
        [MessageCodes.SavedSearchNameTooLong] = "Назва задовга — до {limit} символів.",
        [MessageCodes.SavedSearchLimitReached] = "Більше {limit} збережених пошуків тримати не можна. Видаліть непотрібні.",
        [MessageCodes.DealershipNotAMember] = "Ви не працюєте в цьому салоні.",
        [MessageCodes.DealershipCityUnknown] = "Такого міста немає в довіднику.",
        [MessageCodes.DealershipStaffNoSuchUser] = "Користувача з такою поштою немає.",
        [MessageCodes.DealershipStaffAlready] = "Ця людина вже працює в салоні.",
        [MessageCodes.DealershipStaffNotThere] = "Ця людина не працює в салоні.",
        [MessageCodes.DealershipStaffLastOwner] = "Це єдиний власник салону. Спершу призначте іншого.",
        [MessageCodes.DealershipStaffOwnerOnly] = "Керувати персоналом може лише власник салону.",
        [MessageCodes.AdminBanSelf] = "Заблокувати власний акаунт не можна.",
        [MessageCodes.AdminRoleSelfDemote] = "Зняти з себе роль адміністратора не можна.",
        [MessageCodes.AdminRoleUnknown] = "Ролі «{role}» не існує.",
        [MessageCodes.ChatOwnListing] = "Це ваше оголошення — писати нема кому.",
        [MessageCodes.TitleListingNotFound] = "Оголошення не знайдено",
        [MessageCodes.TitleQuestionNotFound] = "Питання не знайдено",
        [MessageCodes.TitleReportNotFound] = "Скаргу не знайдено",
        [MessageCodes.TitleReportNotAllowed] = "Скаржитися не можна",
        [MessageCodes.TitleReviewNotAllowed] = "Відгук лишити не можна",
        [MessageCodes.TitleSavedSearchNotFound] = "Збережений пошук не знайдено",
        [MessageCodes.TitlePlanNotFound] = "Тариф не знайдено",
        [MessageCodes.TitleSubscriptionNotAllowed] = "Оформити не можна",
        [MessageCodes.TitleInsufficientFunds] = "Недостатньо коштів",
        [MessageCodes.TitleNoAccess] = "Немає доступу",
        [MessageCodes.TitleDealershipNotFound] = "Салон не знайдено",
        [MessageCodes.TitleUserNotFound] = "Користувача не знайдено",
        [MessageCodes.TitleAdminActionForbidden] = "Дію заборонено",
        [MessageCodes.TitleConversationNotFound] = "Розмову не знайдено",
        [MessageCodes.TitleChatNotAllowed] = "Листування неможливе",
        [MessageCodes.TitleInvalidData] = "Некоректні дані",
        [MessageCodes.TitleAuctionNotFound] = "Торгів не знайдено",
        [MessageCodes.TitleBiddingNotAllowed] = "Ставити не можна",
        [MessageCodes.TitleInvalidLocation] = "Некоректне місцезнаходження",
        [MessageCodes.TitleRuleViolated] = "Дію зараз виконати не можна",
        [MessageCodes.SavedSearchNameEmpty] = "Назва пошуку не може бути порожньою.",
        [MessageCodes.DetailListingNotFound] = "Оголошення {id} не знайдено.",
        [MessageCodes.DetailQuestionNotFound] = "Питання {id} не знайдено.",
        [MessageCodes.DetailReportNotFound] = "Скаргу {id} не знайдено.",
        [MessageCodes.DetailAuctionNotFound] = "Торгів для оголошення {id} не знайдено.",
        [MessageCodes.DetailDealershipNotFound] = "Салон {id} не знайдено.",
        [MessageCodes.DetailUserNotFound] = "Користувача {id} не знайдено.",
        [MessageCodes.DetailConversationNotFound] = "Розмову {id} не знайдено.",
        [MessageCodes.DetailPlanNotFound] = "Тарифного плану «{id}» не існує.",
        [MessageCodes.DetailSavedSearchNotFound] = "Збережений пошук {id} не знайдено.",
        [MessageCodes.DetailInsufficientFunds] = "На балансі {available}, а потрібно {required}.",
    };

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        [MessageCodes.AuthEmailRequired] = "Enter an e-mail address.",
        [MessageCodes.AuthEmailTooLong] = "That e-mail address is too long.",
        [MessageCodes.AuthEmailMalformed] = "That e-mail address does not look right.",
        [MessageCodes.AuthPasswordRequired] = "Enter a password.",
        [MessageCodes.AuthPasswordTooShort] = "The password must be at least 8 characters long.",
        [MessageCodes.AuthPasswordTooLong] = "That password is too long.",
        [MessageCodes.AuthPasswordNeedsLower] = "The password must contain a lower-case letter.",
        [MessageCodes.AuthPasswordNeedsUpper] = "The password must contain an upper-case letter.",
        [MessageCodes.AuthPasswordNeedsDigit] = "The password must contain a digit.",
        [MessageCodes.AuthDisplayNameRequired] = "Enter your name or the dealership's name.",
        [MessageCodes.AuthDisplayNameTooShort] = "That name is too short.",
        [MessageCodes.AuthDisplayNameTooLong] = "That name is too long.",
        [MessageCodes.AuthAccountTypeUnknown] = "Unknown account type.",
        [MessageCodes.AuthPhoneFormat] = "The phone number must be in the format +380XXXXXXXXX.",
        [MessageCodes.RecoveryEmailRequired] = "Enter your e-mail address.",
        [MessageCodes.RecoveryEmailMalformed] = "That e-mail address does not look right.",
        [MessageCodes.RecoveryEmailTooLong] = "That address is too long.",
        [MessageCodes.RecoveryTokenIncomplete] = "The link is incomplete — use the one from the letter.",
        [MessageCodes.RecoveryPasswordRequired] = "Enter a new password.",
        [MessageCodes.PlaceCityInvalid] = "That city identifier is not valid.",
        [MessageCodes.PlaceDistrictInvalid] = "That city district identifier is not valid.",
        [MessageCodes.PlaceCityFirst] = "Choose a city first.",
        [MessageCodes.ProfileDisplayNameRequired] = "Tell us what to call you.",
        [MessageCodes.CarVinFormat] = "A VIN is 17 characters long and never contains the letters I, O or Q.",
        [MessageCodes.CarMakeRequired] = "Choose a make.",
        [MessageCodes.CarModelRequired] = "Choose a model.",
        [MessageCodes.CarGenerationInvalid] = "That generation is not valid.",
        [MessageCodes.CarFeaturesDuplicate] = "One of the features is listed twice.",
        [MessageCodes.CarFeaturesInvalid] = "That feature is not valid.",
        [MessageCodes.CarConditionUnknown] = "Unknown condition.",
        [MessageCodes.CarMileageRequired] = "Enter the mileage.",
        [MessageCodes.CarMileageUnrealistic] = "That mileage does not look realistic.",
        [MessageCodes.CarMileageNewTooHigh] = "A new car cannot have mileage that high.",
        [MessageCodes.CarOwnersNewHasNone] = "A new car has not had any owners yet.",
        [MessageCodes.CarOwnersUnrealistic] = "That number of owners does not look realistic.",
        [MessageCodes.CarFuelUnknown] = "Unknown fuel type.",
        [MessageCodes.CarTransmissionUnknown] = "Unknown transmission type.",
        [MessageCodes.CarDrivetrainUnknown] = "Unknown drivetrain type.",
        [MessageCodes.CarEngineRequired] = "Enter the engine size.",
        [MessageCodes.CarEngineNotForElectric] = "An electric car has no engine size.",
        [MessageCodes.CarEngineRange] = "The engine size must be between 0.1 and 12 litres.",
        [MessageCodes.CarPowerRange] = "Power must be between 1 and 2000 hp.",
        [MessageCodes.CarConsumptionCityUnrealistic] = "That urban consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionHighwayUnrealistic] = "That motorway consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionCombinedUnrealistic] = "That combined consumption figure does not look realistic.",
        [MessageCodes.CarConsumptionNotForElectric] = "An electric car does not consume fuel.",
        [MessageCodes.CarBatteryRequired] = "Enter the battery capacity.",
        [MessageCodes.CarBatteryOnlyElectric] = "Only an electric car or a hybrid has a battery.",
        [MessageCodes.CarBatteryRange] = "Battery capacity must be between 1 and 300 kWh.",
        [MessageCodes.CarRangeUnrealistic] = "That range does not look realistic.",
        [MessageCodes.CarRangeNeedsBattery] = "Range is only given where there is a battery.",
        [MessageCodes.CarChargingPortNeedsBattery] = "A charging port only exists where there is a battery.",
        [MessageCodes.CarChargingPortUnknown] = "Unknown charging port type.",
        [MessageCodes.CarBodyUnknown] = "Unknown body type.",
        [MessageCodes.CarColourUnknown] = "Unknown colour.",
        [MessageCodes.CarDamageUnknown] = "Unknown damage state.",
        [MessageCodes.CarSeatsRange] = "The number of seats must be between 1 and 9.",
        [MessageCodes.CarDoorsRange] = "The number of doors must be between 2 and 6.",
        [MessageCodes.CarEcologyUnknown] = "Unknown emission standard.",
        [MessageCodes.CarPaintUnknown] = "Unknown paint condition.",
        [MessageCodes.CarImportedFromInvalid] = "That country of import is not valid.",
        [MessageCodes.CarManufacturerCountryInvalid] = "That country of manufacture is not valid.",
        [MessageCodes.ListingTitleRequired] = "Enter a title.",
        [MessageCodes.ListingTitleTooShort] = "That title is too short.",
        [MessageCodes.ListingTitleTooLong] = "That title is too long.",
        [MessageCodes.ListingDescriptionRequired] = "Add a description.",
        [MessageCodes.ListingDescriptionTooShort] = "That description is too short.",
        [MessageCodes.ListingDescriptionTooLong] = "That description is too long.",
        [MessageCodes.ListingCityRequired] = "Choose a city.",
        [MessageCodes.ListingDistrictInvalid] = "That city district is not valid.",
        [MessageCodes.ListingPricePositive] = "The price must be greater than zero.",
        [MessageCodes.ListingPriceUnrealistic] = "That price looks like a mistake.",
        [MessageCodes.ListingCurrencyUnknown] = "Unknown currency.",
        [MessageCodes.ListingTypeUnknown] = "Unknown listing type.",
        [MessageCodes.ListingReserveBelowStart] = "The reserve price cannot be lower than the starting price.",
        [MessageCodes.ListingReserveAuctionOnly] = "Only an auction lot has a reserve price.",
        [MessageCodes.ModerationReasonRequired] = "Give a reason for the rejection.",
        [MessageCodes.ModerationReasonTooShort] = "The reason should explain what needs fixing.",
        [MessageCodes.ModerationReasonTooLong] = "That reason is too long.",
        [MessageCodes.QuestionTextRequired] = "A question cannot be empty.",
        [MessageCodes.QuestionTextTooShort] = "That question is too short.",
        [MessageCodes.QuestionTextTooLong] = "That question is too long — 1000 characters at most.",
        [MessageCodes.QuestionAnswerRequired] = "An answer cannot be empty.",
        [MessageCodes.QuestionAnswerTooLong] = "That answer is too long — 2000 characters at most.",
        [MessageCodes.ReportReasonRequired] = "Choose a reason from the list.",
        [MessageCodes.ReportCommentTooLong] = "That explanation is too long — 1000 characters at most.",
        [MessageCodes.ReportCommentRequired] = "Describe what the problem is.",
        [MessageCodes.ReportNoteTooLong] = "That note is too long — 1000 characters at most.",
        [MessageCodes.CatalogPageMin] = "Page numbers start at one.",
        [MessageCodes.CatalogTextTooLong] = "That search query is too long.",
        [MessageCodes.CatalogSortUnknown] = "Unknown sort order.",
        [MessageCodes.CatalogPriceRange] = "The lower price bound is above the upper one.",
        [MessageCodes.CatalogYearRange] = "The lower year bound is above the upper one.",
        [MessageCodes.CatalogMileageRange] = "The lower mileage bound is above the upper one.",
        [MessageCodes.CatalogEngineRange] = "The lower engine-size bound is above the upper one.",
        [MessageCodes.CatalogPowerRange] = "The lower power bound is above the upper one.",
        [MessageCodes.ChatMessageRequired] = "A message cannot be empty.",
        [MessageCodes.ChatMessageTooLong] = "That message is too long — 4000 characters at most.",
        [MessageCodes.SavedSearchNameRequired] = "Give the search a name.",
        [MessageCodes.ListingSubmitWrongStatus] = "Only a draft or a rejected listing can be submitted for moderation.",
        [MessageCodes.ListingApproveWrongStatus] = "Only a listing awaiting moderation can be approved.",
        [MessageCodes.ListingRejectWrongStatus] = "Only a listing awaiting moderation can be rejected.",
        [MessageCodes.ListingUnpublishWrongStatus] = "Only a published listing can be taken down.",
        [MessageCodes.ListingSoldWrongStatus] = "Only an active listing can be marked as sold.",
        [MessageCodes.ListingSoldSellerIsBuyer] = "The seller cannot be the buyer.",
        [MessageCodes.ListingArchiveAlready] = "The listing is already archived.",
        [MessageCodes.ListingArchiveDraft] = "A draft is not archived — it is deleted.",
        [MessageCodes.ListingRestoreWrongStatus] = "Only an archived listing can be restored.",
        [MessageCodes.ListingEditWrongStatus] = "Only a draft or a rejected listing can be edited.",
        [MessageCodes.ListingDeleteDraftOnly] = "Only a draft can be deleted; a published listing is archived.",
        [MessageCodes.ListingAccessOtherSeller] = "This listing belongs to another seller.",
        [MessageCodes.ListingBuyerNeverWrote] = "This person never wrote to you about this car, so they cannot be the buyer.",
        [MessageCodes.ListingLimitReached] = "Your plan allows {limit} active listings. Archive some, or move to a higher plan.",
        [MessageCodes.CarModelWrongMake] = "The chosen model does not belong to that make.",
        [MessageCodes.CarGenerationWrongModel] = "The chosen generation does not belong to that model.",
        [MessageCodes.CarFeaturesUnknownSome] = "Some of the chosen features are unknown.",
        [MessageCodes.PlaceCityOrDistrictInvalid] = "There is no such city, or that district belongs to a different one.",
        [MessageCodes.PhotoNotAnImage] = "That file is not an image.",
        [MessageCodes.PhotoFormatUnsupported] = "Only JPEG, PNG and WebP are supported.",
        [MessageCodes.PhotoResolutionTooBig] = "That image has too high a resolution.",
        [MessageCodes.PhotoCorrupt] = "The file is damaged, or it is not an image.",
        [MessageCodes.PhotoOrderMustListAll] = "The list must contain every photograph of the listing exactly once.",
        [MessageCodes.PhotoLimitReached] = "A listing takes no more than {limit} photographs.",
        [MessageCodes.PhotoTooLarge] = "That file is too large: {limit} MB at most.",
        [MessageCodes.QuestionSelf] = "You cannot ask yourself — answer other people's questions instead.",
        [MessageCodes.QuestionAnswerSellerOnly] = "Only the seller can answer questions.",
        [MessageCodes.ReportOwnListing] = "This is your own listing.",
        [MessageCodes.ReportAlreadyResolved] = "That report has already been dealt with.",
        [MessageCodes.ReviewSelf] = "Reviewing yourself makes no sense.",
        [MessageCodes.ReviewPartiesOnly] = "Only the two sides of the deal — the seller and the buyer — can leave a review.",
        [MessageCodes.ReviewAlready] = "You have already reviewed this deal.",
        [MessageCodes.ReviewRatingRange] = "The rating must be between {min} and {max}.",
        [MessageCodes.AuctionBidTooLow] = "The bid must be at least {minimum} — that is the current price plus the increment.",
        [MessageCodes.AuctionCeilingTooLow] = "The new ceiling must be higher than the previous one.",
        [MessageCodes.AuctionFinished] = "Bidding has already ended.",
        [MessageCodes.AuctionTimeUp] = "Time for this auction has run out.",
        [MessageCodes.AuctionStillRunning] = "Bidding is still under way — it is too early to close.",
        [MessageCodes.AuctionOwnLot] = "You cannot bid on your own lot.",
        [MessageCodes.WalletTopUpPositive] = "The top-up amount must be positive.",
        [MessageCodes.WalletChargePositive] = "The amount charged must be positive.",
        [MessageCodes.WalletTopUpMax] = "You can top up by no more than {limit} at a time.",
        [MessageCodes.BillingBasicNoOrder] = "The basic plan needs no subscribing to — simply wait for the paid one to end.",
        [MessageCodes.BillingPlanWaitForEnd] = "Your current plan has to end first — switching mid-period is not provided for.",
        [MessageCodes.SavedSearchNameTooLong] = "That name is too long — {limit} characters at most.",
        [MessageCodes.SavedSearchLimitReached] = "You cannot keep more than {limit} saved searches. Delete the ones you no longer need.",
        [MessageCodes.DealershipNotAMember] = "You do not work at this dealership.",
        [MessageCodes.DealershipCityUnknown] = "There is no such city in the reference data.",
        [MessageCodes.DealershipStaffNoSuchUser] = "There is no user with that e-mail address.",
        [MessageCodes.DealershipStaffAlready] = "This person already works at the dealership.",
        [MessageCodes.DealershipStaffNotThere] = "This person does not work at the dealership.",
        [MessageCodes.DealershipStaffLastOwner] = "This is the dealership's only owner. Appoint another one first.",
        [MessageCodes.DealershipStaffOwnerOnly] = "Only the dealership's owner can manage its staff.",
        [MessageCodes.AdminBanSelf] = "You cannot ban your own account.",
        [MessageCodes.AdminRoleSelfDemote] = "You cannot take the administrator role away from yourself.",
        [MessageCodes.AdminRoleUnknown] = "There is no role called “{role}”.",
        [MessageCodes.ChatOwnListing] = "This is your own listing — there is no one to write to.",
        [MessageCodes.TitleListingNotFound] = "Listing not found",
        [MessageCodes.TitleQuestionNotFound] = "Question not found",
        [MessageCodes.TitleReportNotFound] = "Report not found",
        [MessageCodes.TitleReportNotAllowed] = "Reporting is not allowed",
        [MessageCodes.TitleReviewNotAllowed] = "You cannot leave a review",
        [MessageCodes.TitleSavedSearchNotFound] = "Saved search not found",
        [MessageCodes.TitlePlanNotFound] = "Plan not found",
        [MessageCodes.TitleSubscriptionNotAllowed] = "You cannot subscribe",
        [MessageCodes.TitleInsufficientFunds] = "Not enough funds",
        [MessageCodes.TitleNoAccess] = "No access",
        [MessageCodes.TitleDealershipNotFound] = "Dealership not found",
        [MessageCodes.TitleUserNotFound] = "User not found",
        [MessageCodes.TitleAdminActionForbidden] = "That action is forbidden",
        [MessageCodes.TitleConversationNotFound] = "Conversation not found",
        [MessageCodes.TitleChatNotAllowed] = "Messaging is not possible",
        [MessageCodes.TitleInvalidData] = "Invalid data",
        [MessageCodes.TitleAuctionNotFound] = "Auction not found",
        [MessageCodes.TitleBiddingNotAllowed] = "You cannot bid",
        [MessageCodes.TitleInvalidLocation] = "Invalid location",
        [MessageCodes.TitleRuleViolated] = "That action cannot be carried out right now",
        [MessageCodes.SavedSearchNameEmpty] = "The search name cannot be empty.",
        [MessageCodes.DetailListingNotFound] = "Listing {id} was not found.",
        [MessageCodes.DetailQuestionNotFound] = "Question {id} was not found.",
        [MessageCodes.DetailReportNotFound] = "Report {id} was not found.",
        [MessageCodes.DetailAuctionNotFound] = "No auction was found for listing {id}.",
        [MessageCodes.DetailDealershipNotFound] = "Dealership {id} was not found.",
        [MessageCodes.DetailUserNotFound] = "User {id} was not found.",
        [MessageCodes.DetailConversationNotFound] = "Conversation {id} was not found.",
        [MessageCodes.DetailPlanNotFound] = "There is no plan called “{id}”.",
        [MessageCodes.DetailSavedSearchNotFound] = "Saved search {id} was not found.",
        [MessageCodes.DetailInsufficientFunds] = "Your balance is {available}, and {required} is needed.",
    };

    /// <summary>Коди, для яких є переклад. Потрібно тестам.</summary>
    public static IReadOnlyCollection<string> Codes => Ukrainian.Keys;

    /// <summary>
    /// Перекладає код. Незнайомий рядок повертається як є — і це навмисно:
    /// так повідомлення, яке ще не перевели на коди, показується старим
    /// текстом замість того, щоб зникнути або перетворитися на «null».
    /// </summary>
    public static string Translate(string codeOrText, string language)
    {
        var table = LanguageCodes.Normalize(language) == LanguageCodes.English ? English : Ukrainian;

        return table.TryGetValue(codeOrText, out var text) ? text : codeOrText;
    }

    /// <summary>
    /// Те саме з підстановкою значень: «до {limit} фото» перетворюється на
    /// «до 20 фото». Невідоме ім'я лишається як є — краще побачити на екрані
    /// «{limit}» і зрозуміти, де саме недогляд, ніж мовчазну порожнечу.
    /// </summary>
    public static string Translate(
        string codeOrText,
        string language,
        IReadOnlyDictionary<string, object?> values)
    {
        ArgumentNullException.ThrowIfNull(values);

        var text = Translate(codeOrText, language);

        if (values.Count == 0)
        {
            return text;
        }

        return PlaceholderPattern().Replace(text, match =>
        {
            var name = match.Groups[1].Value;

            return values.TryGetValue(name, out var value)
                ? Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty
                : match.Value;
        });
    }

    [GeneratedRegex(@"\{(\w+)\}")]
    private static partial Regex PlaceholderPattern();
}
