// <auto-generated />
using System;
using AutoLot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoLot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutoLotDbContext))]
    [Migration("20260823181738_AddPhotoThumbnails")]
    partial class AddPhotoThumbnails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoLot.Domain.Cars.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_features");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_features_code");

                    b.HasIndex("Category", "SortOrder")
                        .HasDatabaseName("ix_features_category_sort_order");

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.FeatureTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FeatureId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_feature_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_feature_translations_name");

                    b.HasIndex("FeatureId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_feature_translations_feature_id_language");

                    b.ToTable("feature_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Generation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<int>("YearFrom")
                        .HasColumnType("integer")
                        .HasColumnName("year_from");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer")
                        .HasColumnName("year_to");

                    b.HasKey("Id")
                        .HasName("pk_generations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_generations_slug");

                    b.HasIndex("ModelId", "YearFrom")
                        .HasDatabaseName("ix_generations_model_id_year_from");

                    b.ToTable("generations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Make", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean")
                        .HasColumnName("is_popular");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_makes");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_makes_slug");

                    b.HasIndex("IsPopular", "Name")
                        .HasDatabaseName("ix_makes_is_popular_name");

                    b.ToTable("makes", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Model", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MakeId")
                        .HasColumnType("bigint")
                        .HasColumnName("make_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_models_slug");

                    b.HasIndex("MakeId", "Name")
                        .HasDatabaseName("ix_models_make_id_name");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Common.EnumTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EnumName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("enum_name");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_enum_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_enum_translations_name");

                    b.HasIndex("EnumName", "Value", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_enum_translations_enum_name_value_language");

                    b.ToTable("enum_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("district_id");

                    b.Property<bool>("IsRegionCentre")
                        .HasColumnType("boolean")
                        .HasColumnName("is_region_centre");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_code");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_cities_district_id");

                    b.HasIndex("RegionId", "Population")
                        .HasDatabaseName("ix_cities_region_id_population");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityDistrict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_city_districts");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_city_districts_city_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_city_districts_code");

                    b.ToTable("city_districts", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityDistrictTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityDistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_district_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_city_district_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_city_district_translations_name");

                    b.HasIndex("CityDistrictId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_city_district_translations_city_district_id_language");

                    b.ToTable("city_district_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_city_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_city_translations_name");

                    b.HasIndex("CityId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_city_translations_city_id_language");

                    b.ToTable("city_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CountryTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_country_translations_name");

                    b.HasIndex("CountryId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_country_translations_country_id_language");

                    b.ToTable("country_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_districts_code");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_districts_region_id");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.DistrictTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("district_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_district_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_district_translations_name");

                    b.HasIndex("DistrictId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_district_translations_district_id_language");

                    b.ToTable("district_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_code");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.RegionTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_region_translations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_region_translations_name");

                    b.HasIndex("RegionId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_region_translations_region_id_language");

                    b.ToTable("region_translations", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_family_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("account_type");

                    b.Property<long?>("CityDistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_district_id");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountType")
                        .HasDatabaseName("ix_users_account_type");

                    b.HasIndex("CityDistrictId")
                        .HasDatabaseName("ix_users_city_district_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_users_city_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BatteryCapacity")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("battery_capacity");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("body_type");

                    b.Property<string>("ChargingPort")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("charging_port");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("condition");

                    b.Property<string>("DamageState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("damage_state");

                    b.Property<int?>("DoorCount")
                        .HasColumnType("integer")
                        .HasColumnName("door_count");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("drivetrain");

                    b.Property<string>("EcologyStandard")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ecology_standard");

                    b.Property<int?>("ElectricRange")
                        .HasColumnType("integer")
                        .HasColumnName("electric_range");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("integer")
                        .HasColumnName("engine_power");

                    b.Property<decimal?>("EngineVolume")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("engine_volume");

                    b.Property<decimal?>("FuelConsumptionCity")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("fuel_consumption_city");

                    b.Property<decimal?>("FuelConsumptionCombined")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("fuel_consumption_combined");

                    b.Property<decimal?>("FuelConsumptionHighway")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("fuel_consumption_highway");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("fuel_type");

                    b.Property<long?>("GenerationId")
                        .HasColumnType("bigint")
                        .HasColumnName("generation_id");

                    b.Property<bool>("HasServiceBook")
                        .HasColumnType("boolean")
                        .HasColumnName("has_service_book");

                    b.Property<long?>("ImportedFromCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_from_country_id");

                    b.Property<bool>("IsCustomsCleared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_customs_cleared");

                    b.Property<bool>("IsGarageKept")
                        .HasColumnType("boolean")
                        .HasColumnName("is_garage_kept");

                    b.Property<bool>("IsLocatedInUkraine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_located_in_ukraine");

                    b.Property<bool>("IsMetallic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_metallic");

                    b.Property<bool>("IsOnCredit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on_credit");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint")
                        .HasColumnName("listing_id");

                    b.Property<long>("MakeId")
                        .HasColumnType("bigint")
                        .HasColumnName("make_id");

                    b.Property<long?>("ManufacturerCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("manufacturer_country_id");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<int?>("OwnerCount")
                        .HasColumnType("integer")
                        .HasColumnName("owner_count");

                    b.Property<string>("PaintCondition")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("paint_condition");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("transmission");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<bool>("WasInAccident")
                        .HasColumnType("boolean")
                        .HasColumnName("was_in_accident");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.HasIndex("BodyType")
                        .HasDatabaseName("ix_cars_body_type");

                    b.HasIndex("FuelType")
                        .HasDatabaseName("ix_cars_fuel_type");

                    b.HasIndex("GenerationId")
                        .HasDatabaseName("ix_cars_generation_id");

                    b.HasIndex("ImportedFromCountryId")
                        .HasDatabaseName("ix_cars_imported_from_country_id");

                    b.HasIndex("ListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_cars_listing_id");

                    b.HasIndex("ManufacturerCountryId")
                        .HasDatabaseName("ix_cars_manufacturer_country_id");

                    b.HasIndex("Mileage")
                        .HasDatabaseName("ix_cars_mileage");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_cars_model_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_cars_year");

                    b.HasIndex("MakeId", "ModelId")
                        .HasDatabaseName("ix_cars_make_id_model_id");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.CarFeature", b =>
                {
                    b.Property<long>("CarId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_id");

                    b.Property<long>("FeatureId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_id");

                    b.HasKey("CarId", "FeatureId")
                        .HasName("pk_car_features");

                    b.HasIndex("FeatureId")
                        .HasDatabaseName("ix_car_features_feature_id");

                    b.ToTable("car_features", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.CarPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("thumbnail_path");

                    b.HasKey("Id")
                        .HasName("pk_car_photos");

                    b.HasIndex("CarId", "SortOrder")
                        .HasDatabaseName("ix_car_photos_car_id_sort_order");

                    b.ToTable("car_photos", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Listing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcceptsTrade")
                        .HasColumnType("boolean")
                        .HasColumnName("accepts_trade");

                    b.Property<long?>("CityDistrictId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_district_id");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsNegotiable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_negotiable");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("PriceUah")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_uah");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("CityDistrictId")
                        .HasDatabaseName("ix_listings_city_district_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_listings_city_id");

                    b.HasIndex("SellerId", "Status")
                        .HasDatabaseName("ix_listings_seller_id_status");

                    b.HasIndex("Status", "PriceUah")
                        .HasDatabaseName("ix_listings_status_price_uah");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("ix_listings_status_published_at");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.FeatureTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Cars.Feature", "Feature")
                        .WithMany("Translations")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feature_translations_features_feature_id");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Generation", b =>
                {
                    b.HasOne("AutoLot.Domain.Cars.Model", "Model")
                        .WithMany("Generations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generations_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Model", b =>
                {
                    b.HasOne("AutoLot.Domain.Cars.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_models_makes_make_id");

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.City", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.District", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cities_districts_district_id");

                    b.HasOne("AutoLot.Domain.Geo.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cities_regions_region_id");

                    b.Navigation("District");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityDistrict", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.City", "City")
                        .WithMany("CityDistricts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_city_districts_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityDistrictTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.CityDistrict", "CityDistrict")
                        .WithMany("Translations")
                        .HasForeignKey("CityDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_city_district_translations_city_districts_city_district_id");

                    b.Navigation("CityDistrict");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.City", "City")
                        .WithMany("Translations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_city_translations_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CountryTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.Country", "Country")
                        .WithMany("Translations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_country_translations_countries_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.District", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.Region", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_districts_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.DistrictTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.District", "District")
                        .WithMany("Translations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_district_translations_districts_district_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.RegionTranslation", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.Region", "Region")
                        .WithMany("Translations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_translations_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.User", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.CityDistrict", "CityDistrict")
                        .WithMany()
                        .HasForeignKey("CityDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_city_districts_city_district_id");

                    b.HasOne("AutoLot.Domain.Geo.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_cities_city_id");

                    b.Navigation("City");

                    b.Navigation("CityDistrict");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Car", b =>
                {
                    b.HasOne("AutoLot.Domain.Cars.Generation", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cars_generations_generation_id");

                    b.HasOne("AutoLot.Domain.Geo.Country", "ImportedFromCountry")
                        .WithMany()
                        .HasForeignKey("ImportedFromCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cars_countries_imported_from_country_id");

                    b.HasOne("AutoLot.Domain.Listings.Listing", "Listing")
                        .WithOne("Car")
                        .HasForeignKey("AutoLot.Domain.Listings.Car", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cars_listings_listing_id");

                    b.HasOne("AutoLot.Domain.Cars.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_makes_make_id");

                    b.HasOne("AutoLot.Domain.Geo.Country", "ManufacturerCountry")
                        .WithMany()
                        .HasForeignKey("ManufacturerCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cars_countries_manufacturer_country_id");

                    b.HasOne("AutoLot.Domain.Cars.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cars_models_model_id");

                    b.Navigation("Generation");

                    b.Navigation("ImportedFromCountry");

                    b.Navigation("Listing");

                    b.Navigation("Make");

                    b.Navigation("ManufacturerCountry");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.CarFeature", b =>
                {
                    b.HasOne("AutoLot.Domain.Listings.Car", "Car")
                        .WithMany("Features")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_features_cars_car_id");

                    b.HasOne("AutoLot.Domain.Cars.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_car_features_features_feature_id");

                    b.Navigation("Car");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.CarPhoto", b =>
                {
                    b.HasOne("AutoLot.Domain.Listings.Car", "Car")
                        .WithMany("Photos")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_photos_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Listing", b =>
                {
                    b.HasOne("AutoLot.Domain.Geo.CityDistrict", "CityDistrict")
                        .WithMany()
                        .HasForeignKey("CityDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_city_districts_city_district_id");

                    b.HasOne("AutoLot.Domain.Geo.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_cities_city_id");

                    b.HasOne("AutoLot.Domain.Identity.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_seller_id");

                    b.Navigation("City");

                    b.Navigation("CityDistrict");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AutoLot.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("AutoLot.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Feature", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AutoLot.Domain.Cars.Model", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.City", b =>
                {
                    b.Navigation("CityDistricts");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.CityDistrict", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.Country", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.District", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Geo.Region", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Districts");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AutoLot.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Car", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AutoLot.Domain.Listings.Listing", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
